const DATA = [{
  "id": 1,
  "first_name": "Billy",
  "last_name": "MacGeffen",
  "email": "bmacgeffen0@arstechnica.com",
  "gender": "Male",
  "ip_address": "131.29.165.79"
}, {
  "id": 2,
  "first_name": "Roseanne",
  "last_name": "Philippsohn",
  "email": "rphilippsohn1@pbs.org",
  "gender": "Female",
  "ip_address": "214.248.145.14"
}, {
  "id": 3,
  "first_name": "Ab",
  "last_name": "Michurin",
  "email": "amichurin2@cargocollective.com",
  "gender": "Male",
  "ip_address": "96.121.81.221"
}, {
  "id": 4,
  "first_name": "Ranna",
  "last_name": "Bradburne",
  "email": "rbradburne3@bigcartel.com",
  "gender": "Female",
  "ip_address": "23.214.117.43"
}, {
  "id": 5,
  "first_name": "Goldi",
  "last_name": "Hosby",
  "email": "ghosby4@alibaba.com",
  "gender": "Female",
  "ip_address": "171.139.173.44"
}, {
  "id": 6,
  "first_name": "Sabine",
  "last_name": "Whitesel",
  "email": "swhitesel5@toplist.cz",
  "gender": "Female",
  "ip_address": "2.49.91.89"
}, {
  "id": 7,
  "first_name": "Penny",
  "last_name": "Phillcock",
  "email": "pphillcock6@utexas.edu",
  "gender": "Female",
  "ip_address": "2.53.65.242"
}, {
  "id": 8,
  "first_name": "Hillary",
  "last_name": "Matthius",
  "email": "hmatthius7@nih.gov",
  "gender": "Male",
  "ip_address": "128.218.31.100"
}, {
  "id": 9,
  "first_name": "Heinrick",
  "last_name": "Ower",
  "email": "hower8@a8.net",
  "gender": "Male",
  "ip_address": "161.122.113.56"
}, {
  "id": 10,
  "first_name": "Jard",
  "last_name": "Wortley",
  "email": "jwortley9@nymag.com",
  "gender": "Male",
  "ip_address": "33.80.167.9"
}];

export default DATA;
